###
GET http://localhost:5001/api/user

###
GET http://localhost:5001/api/user/1

###
POST http://localhost:5001/api/user/
Content-Type: application/json

{
  "name": "Admin2",
  "email": "admin2@test.com"
  }

###
PUT http://localhost:5001/api/user/1
Content-Type: application/json

{
  "name": "John",
  "email": "john@test.com"
  }

###
DELETE http://localhost:5001/api/user/1



###
GET http://localhost:5001/api/accommodations

###
GET http://localhost:5001/api/accommodations/85f28f9e-537f-45b3-ba78-4b24380cfe50

###
GET http://localhost:5001/api/accommodations/type/resort/

###
POST http://localhost:5001/api/accommodations/
Content-Type: application/json

{
  "name": "HOTEL B",
  "address": "Alagbaka Road, Enugu",
  "localGovt": "Ondo South",
  "description": "This is HOTEL B",
  "slug": "hotel-b",
  "type": "Hotel"
  }


###
PUT http://localhost:5001/api/accommodations/1
Content-Type: application/json

{
  "name": "HOTEL A",
  "address": "FUTA Road, Akure",
  "description": "This is HOTEL A",
  "type": "Hotel"

  }
###
DELETE http://localhost:5001/api/accommodations/85f28f9e-537f-45b3-ba78-4b24380cfe50
